steps:
  - id: "Activate virtual environment venv"
    name: 'gcr.io/your_project_id/dataflow-python3:latest'
    entrypoint: '/bin/bash'
    args: [ '-c', 'source /venv/bin/activate' ]
    waitFor: ['-']

  - id: "Create dataflow template"
    name: 'gcr.io/your_project_id/dataflow-python3:latest'
    entrypoint: 'python'
    args: [ '-m', 'main',
         "--job_name=your_job_name",
         "--project=your_project_id", 
         "--region=us-east1",
         "--template_location=gs://your_project_id-dataflow-templates/my-template/templates/template_test",
         "--staging_location=gs://your_project_id-dataflow-templates/my-template/staging/",
         "--temp_location=gs://your_project_id-dataflow-templates/my-template/temp/",
         "--runner=DataflowRunner",
         "--setup_file='./setup.py'",
         "--autoscaling_algorithm=NONE"
         ]
    waitFor: [
      'Activate virtual environment venv'
      ]